ExamenReclutamiento/Models/ErrorViewModel.cs
using System;

namespace ExamenReclutamiento.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenReclutamiento/Models/ProspectoInformacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenReclutamiento.Models
{
    public class ProspectoInformacion
    {
        public Prospectos InformacionProspecto { get; set; }
        public List<Prospecto_Documentacion> DocumentosProsPecto { get; set; }
    }
}

ExamenReclutamiento/Models/Prospecto_Documentacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenReclutamiento.Models
{
    public class Prospecto_Documentacion
    {
        public int id { get; set; }
        public int id_prospecto { get; set; }
        public string nombre_archivo { get; set; }
        public string archivo { get; set; }
    }
}

ExamenReclutamiento/Models/Prospectos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenReclutamiento.Models
{
    public class Prospectos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string aPaterno { get; set; }
        public string aMaterno { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string colonia { get; set; }
        public string codPostal { get; set; }
        public string telefono { get; set; }
        public string rfc { get; set; }
        public string estatus { get; set; }// Enviado, Autorizado o Rechazado
        public string comentario { get; set; }
    }
}

ExamenReclutamiento/Models/ViewModel/VMProspecto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenReclutamiento.Models.ViewModel
{
    public class VMProspecto
    {
        public int id { get; set; }
        public string estatus { get; set; }
        public string comentario { get; set; }
    }
}

ExamenReclutamiento/Controllers/HomeController.cs
using ExamenReclutamiento.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenReclutamiento.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenReclutamiento/Controllers/ProspectoController.cs
using ExamenReclutamiento.Data;
using ExamenReclutamiento.Models;
using ExamenReclutamiento.Models.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenReclutamiento.Controllers
{
    public class ProspectoController : Controller
    {
        private prospectoRepository prosRepository = new prospectoRepository();
        // GET: ProspectoController
        [HttpGet]
        [Route("/captura_prospeto")]
        public ActionResult Captura_prospeto()
        {
            string fileName = System.IO.Path.GetRandomFileName() + Guid.NewGuid().ToString() + ".tmp";
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "Archivos", fileName);
            var filePath2 = Path.GetTempFileName();
            return View();
        }
        [Route("/GuardarProspecto")]
        [HttpPost]
        public async Task<IActionResult> Guardar()
        {
            var formData = await Request.ReadFormAsync();
            Prospectos prospecto = new Prospectos()
            {
                nombre = formData.FirstOrDefault(x => x.Key == "nombre").Value[0],
                aPaterno = formData.FirstOrDefault(x => x.Key == "aPaterno").Value[0],
                aMaterno = formData.FirstOrDefault(x => x.Key == "aMaterno").Value[0],
                calle = formData.FirstOrDefault(x => x.Key == "calle").Value[0],
                numero = formData.FirstOrDefault(x => x.Key == "numero").Value[0],
                colonia = formData.FirstOrDefault(x => x.Key == "colonia").Value[0],
                codPostal = formData.FirstOrDefault(x => x.Key == "codPostal").Value[0],
                telefono = formData.FirstOrDefault(x => x.Key == "telefono").Value[0],
                rfc = formData.FirstOrDefault(x => x.Key == "rfc").Value[0],
                estatus = "Enviado",
                comentario = ""
            };
            List<Prospecto_Documentacion> documentos = new List<Prospecto_Documentacion>();
            int contador = 0;
           
            foreach (var form in formData.Files)
            {
                string fileName = System.IO.Path.GetRandomFileName() + Guid.NewGuid().ToString() + ".tmp";
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "Archivos", fileName);
                var pathString = Path.Combine(Directory.GetCurrentDirectory(), "Archivos");

                if (!Directory.Exists(pathString) )
                {
                    DirectoryInfo di = System.IO.Directory.CreateDirectory(pathString);
                }
                
                using (var stream = System.IO.File.Create(filePath))
                {
                    await form.CopyToAsync(stream);
                }
                Prospecto_Documentacion info = new Prospecto_Documentacion()
                {
                    nombre_archivo = formData.FirstOrDefault(x => x.Key == "archivos_nombres" + contador).Value[0],
                    archivo = filePath
                };
                documentos.Add(info);
                contador++;
            }
            bool resultado =  prosRepository.GuardarProspecto(prospecto, documentos);
            return Json(new
            {
                success = resultado
            });

        }
        [HttpGet]
        [Route("/listado_prospecto")]
        public ActionResult Listado_prospecto()
        {
            return View();
        }
        [HttpGet]
        [Route("/ListadoProspectos")]
        public JsonResult ListaProspecto()
        {
            List<ProspectoInformacion> resultado = prosRepository.ListadoProspectos();
            return Json(new
            {
                success = true,
                listadoProspectos = resultado
            });

        }

        [HttpGet]
        [Route("/evalucion_prospecto")]
        public ActionResult Evalucion_prospecto()
        {
            return View();
        }
        [Route("/AtualizarEstatus")]
        [HttpPost]
        public JsonResult ActulizarProspecto([FromBody] VMProspecto collection)
        {
            bool resultado = prosRepository.actualizarEstatus(collection);
            return Json(new
            {
                success = resultado
            });

        }

    }
}

ExamenReclutamiento/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Ejercicios.</h1>
</div>

ExamenReclutamiento/Views/Prospecto/captura_prospeto.cshtml
@{
    ViewData["Title"] = "captura_prospeto";
}

<div class="col-md-12" ng-controller="FuncionesController"  >
    <h2>Nuevo Prospecto</h2>
    <form enctype="multipart/form-data" name="form" id="form" class="css-form" ng-submit="GuardarInformacion()">
        <div class="row">
            <div class="form-group col-md-4">
                <label>* Nombre:</label>
                <input class="form-control" name="nombre" ng-model="Reg.nombre" required />
            </div>

            <div class="form-group col-md-4">
                <label>* Apellido Paterno:</label>
                <input class="form-control" name="aPaterno" ng-model="Reg.aPaterno" required />
            </div>

            <div class="form-group col-md-4">
                <label>Apellido Materno:</label>
                <input class="form-control" name="aMaterno" ng-model="Reg.aMaterno" />
            </div>
            <div class="form-group col-md-4">
                <label>* Calle:</label>
                <input class="form-control" name="calle" ng-model="Reg.calle" required />
            </div>

            <div class="form-group col-md-4">
                <label>* Numero:</label>
                <input class="form-control" name="numero" ng-model="Reg.numero" required />
            </div>

            <div class="form-group col-md-4">
                <label>* Colonia:</label>
                <input class="form-control" name="colonia" ng-model="Reg.colonia" required />
            </div>

            <div class="form-group col-md-4">
                <label>* CP:</label>
                <input class="form-control" name="codPostal" type="number" ng-model="Reg.codPostal" required />
            </div>

            <div class="form-group col-md-4">
                <label>* Telefono:</label>
                <input class="form-control" name="telefono" ng-model="Reg.telefono" required />
            </div>

            <div class="form-group col-md-4">
                <label>* RFC:</label>
                <input class="form-control" name="rfc" ng-model="Reg.rfc" required />
            </div>

            <h4 style="margin-top:1em;">Documentos adicionales <button type="button" class="btn btn-primary" ng-click="AgregarDocumento()">Agregar</button>
            </h4>

            <div class="container row">

                <div class="col-md-12 row" ng-repeat="(key, doc) in documentoLista track by $index">

                    <div class="col-md-4">
                        <label>* Nombre Documento</label>
                        <input class="form-control" name="Documentos[].Nombre" ng-model="documentoLista[$index].Nombre" required />
                    </div>

                    <div class="col-md-4">
                        <label>* Archivo</label>
                        <input class="form-control" type="file" name="Documentos[].Archivo{{$index}}" ng-model="documentoLista[$index].Archivo" required />
                    </div>

                    <div class="col-md-2" style="margin-top:1.5em;">
                        <button type="button" class="btn btn-danger" ng-click="EliminarDocumento($index)">Eliminar</button>
                    </div>

                </div>


            </div>

            <div class="col-md-12 text-center" style="margin-top:1em;">
                <div class="btn btn-danger" ng-click="SalirProspecto()">Salir</div>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
           </div>
    </form>
</div>

ExamenReclutamiento/Views/Prospecto/evalucion_prospecto.cshtml
@{
    ViewData["Title"] = "evalucion_prospecto";
}
<div class="container-fluid" ng-controller="FuncionesController" ng-init="ListadoProspectos()">
    <div class="modal" tabindex="-1" id="informacionProspecto" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Informacion del Prospecto :{{infoProspecto.nombre}} {{infoProspecto.aPaterno}} {{infoProspecto.aMaterno}}  </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label>* Calle:</label>
                            <input class="form-control" ng-model="infoProspecto.calle" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* Numero:</label>
                            <input class="form-control" ng-model="infoProspecto.numero" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* Colonia:</label>
                            <input class="form-control" ng-model="infoProspecto.colonia" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* CP:</label>
                            <input class="form-control" ng-model="infoProspecto.codPostal" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* Telefono:</label>
                            <input class="form-control" ng-model="infoProspecto.telefono" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* RFC:</label>
                            <input class="form-control" ng-model="infoProspecto.rfc" disabled />
                        </div>

                        <div class="form-group col-md-12" ng-show="infoProspecto.estatus == 'Rechazado'">
                            <label>Motivo del Rechazo:</label>
                            <input class="form-control" ng-model="infoProspecto.comentario" disabled />
                        </div>

                        <h4 style="margin-top:1em;">
                            Documentos adicionales
                        </h4>

                        <div class="container row">

                            <div class="col-md-12 row" ng-repeat="(key, doc) in DocumentosProspecto track by $index">

                                <div class="col-md-6">
                                    <label>Nombre Documento</label><br />
                                    <label>{{DocumentosProspecto[$index].nombre_archivo}}</label>
                                </div>
                                <div class="col-md-6">
                                    <label>Archivo</label><br />
                                    <a class="btn btn-primary" role="button" href="{{DocumentosProspecto[$index].archivo}}" target="_blank">Ver Archivo</a>
                                </div>

                            </div>


                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    
    <h2>Evaluacion de Prospectos</h2>

    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>Apellido Paterno</td>
                    <td>Apellido Materno</td>
                    <td>Estatus</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="pros in prospectos">
                    <td>{{pros.informacionProspecto.nombre}}</td>
                    <td>{{pros.informacionProspecto.aPaterno}}</td>
                    <td>{{pros.informacionProspecto.aMaterno}}</td>
                    <td>{{pros.informacionProspecto.estatus}}</td>
                    <td>
                        <div class="btn btn-secondary" ng-click="InfoProspecto(pros.informacionProspecto,pros.documentosProsPecto)">Ver Datos</div>
                        <div class="btn btn-success" ng-click="CambioEstatus(pros.informacionProspecto,'Autorizado')">Autorizar</div>
                        <div class="btn btn-danger" ng-click="CambioEstatus(pros.informacionProspecto,'Rechazado')">Rechazar</div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>

</div>

ExamenReclutamiento/Views/Prospecto/listado_prospecto.cshtml
@{
    ViewData["Title"] = "listado_prospecto";
}

<div class="container-fluid" ng-controller="FuncionesController" ng-init="ListadoProspectos()">
    <div class="modal" tabindex="-1" id="informacionProspecto" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Informacion del Prospecto :{{infoProspecto.nombre}} {{infoProspecto.aPaterno}} {{infoProspecto.aMaterno}}  </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label>* Calle:</label>
                            <input class="form-control" ng-model="infoProspecto.calle" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* Numero:</label>
                            <input class="form-control" ng-model="infoProspecto.numero" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* Colonia:</label>
                            <input class="form-control" ng-model="infoProspecto.colonia" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* CP:</label>
                            <input class="form-control" ng-model="infoProspecto.codPostal" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* Telefono:</label>
                            <input class="form-control" ng-model="infoProspecto.telefono" disabled />
                        </div>

                        <div class="form-group col-md-12">
                            <label>* RFC:</label>
                            <input class="form-control" ng-model="infoProspecto.rfc" disabled />
                        </div>

                        <div class="form-group col-md-12" ng-show="infoProspecto.estatus == 'Rechazado'">
                            <label>Motivo del Rechazo:</label>
                            <input class="form-control" ng-model="infoProspecto.comentario" disabled />
                        </div>

                        <h4 style="margin-top:1em;">
                            Documentos adicionales
                        </h4>

                        <div class="container row">

                            <div class="col-md-12 row" ng-repeat="(key, doc) in DocumentosProspecto track by $index">

                                <div class="col-md-6">
                                    <label>Nombre Documento</label><br />
                                    <label>{{DocumentosProspecto[$index].nombre_archivo}}</label>
                                </div>
                                <div class="col-md-6">
                                    <label>Archivo</label><br />
                                    <a class="btn btn-primary" role="button" href="{{DocumentosProspecto[$index].archivo}}" target="_blank">Ver Archivo</a>
                                </div>

                            </div>


                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <h2>Listado de Prospectos</h2>

    <div class="row">

        <div class="col-md-4">
            <a class="btn btn-primary" asp-area="" asp-controller="Prospecto" asp-action="captura_prospeto">Captura de Prospecto</a>
        </div>
        <div class="col-md-12">

            <table class="table">
                <thead>
                    <tr>
                        <td>Nombre</td>
                        <td>Apellido Paterno</td>
                        <td>Apellido Materno</td>
                        <td>Estatus</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="pros in prospectos">
                        <td>{{pros.informacionProspecto.nombre}}</td>
                        <td>{{pros.informacionProspecto.aPaterno}}</td>
                        <td>{{pros.informacionProspecto.aMaterno}}</td>
                        <td>{{pros.informacionProspecto.estatus}}</td>
                        <td><div class="btn btn-secondary" ng-click="InfoProspecto(pros.informacionProspecto,pros.documentosProsPecto)">Ver Datos</div></td>
                    </tr>
                </tbody>
            </table>

        </div>

    </div>

</div>

ExamenReclutamiento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenReclutamiento</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/sweetalert/dist/sweetalert2.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ejercicios</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prospecto" asp-action="captura_prospeto">Captura de Prospecto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prospecto" asp-action="listado_prospecto">Listado de Prospecto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prospecto" asp-action="evalucion_prospecto">Evalución de Prospecto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" ng-app="examenRecutamiento">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExamenReclutamiento - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/sweetalert/dist/sweetalert2.js"></script>

    <script src="~/js/site.js"></script>
    <script src="~/js/FuncionesController.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>